server:
  port: 8091
spring:
  application:
    name: api-server-consumer
  main:
    allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。
  datasource:
    druid: # Druid 【监控】相关的全局配置
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        allow: # 设置白名单，不填则允许所有访问
        url-pattern: /druid/*
        login-username: bonc
        login-password: boncadmin
      filter:
        stat:
          enabled: true
          log-slow-sql: true # 慢 SQL 记录
          slow-sql-millis: 100
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
    dynamic: # 多数据源配置
      druid: # Druid 【连接池】相关的全局配置
        initial-size: 5 # 初始连接数
        min-idle: 10 # 最小连接池数量
        max-active: 20 # 最大连接池数量
        max-wait: 600000 # 配置获取连接等待超时的时间，单位：毫秒
        time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位：毫秒
        min-evictable-idle-time-millis: 300000 # 配置一个连接在池中最小生存的时间，单位：毫秒
        max-evictable-idle-time-millis: 900000 # 配置一个连接在池中最大生存的时间，单位：毫秒
        validation-query: SELECT 1 FROM DUAL # 配置检测连接是否有效
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
      primary: apiserver
      datasource:
        apiserver:
          url: jdbc:mysql://10.177.90.14:3306/api_server?allowMultiQueries=true&useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&nullCatalogMeansCurrent=true # MySQL Connector/J 8.X 连接的示例
          username: ENC(IRGv2ha2yNQJA7pfsHiCkFQtIB7TYZ7j)
          password: ENC(Rcw6BRaziGuvSCZpuQnJIcH0DrkQONFe)
        adb:
          url: jdbc:mysql://10.177.158.44:3306/db_zbbq?characterEncoding=UTF-8&useUnicode=true&useSSL=false # MySQL Connector/J 8.X 连接的示例
          username: ENC(9V+28C7WqkWSURCCHFHZGQ==)
          password: ENC(t72ka3B/N7Zfq+xcQcxJ+VJSgNJMJdSz)
  redis:
    password: ENC(lF0MkgwepovpNd8BzPM8KnRh0zr7hBj+)
    database: 0
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
    sentinel:
      master: labeladb
      nodes: 10.177.67.163:32528,10.177.67.165:32525,10.177.67.145:32522
  #################### rocketmq相关配置 ####################
rocketmq:
  #消费者相关配置
  name-server: 10.242.10.63:9876;10.242.18.112:9876
  consumerGroup: GID_API_SERVER_GROUP
  topic: ASYNC_QUERY_SQL
  consumer:
    accessKey: ENC(9/dUZa7QAfk2CCMHXa8um9fU7PqA7B1Z/wg/5mzgYE0=)
    secretKey: ENC(qUrgZXWfzMF/tzWMwipdH6mzoYDYpuKbSzNeTGbOrKYmjFxjbJlXvw==)
  datasetupddatatopic: DATASET_UPDDATA
  upddataConsumerGroup: GID_API_CONSUMER_UPDDATA_DATASET

  #生产者相关配置
  nameSrvSend: 10.242.10.63:9876;10.242.18.112:9876
  producerGroup: GID_SERVICE_CALLER_GROUP
  accessKey: ENC(9/dUZa7QAfk2CCMHXa8um9fU7PqA7B1Z/wg/5mzgYE0=)
  secretKey: ENC(qUrgZXWfzMF/tzWMwipdH6mzoYDYpuKbSzNeTGbOrKYmjFxjbJlXvw==)
  async-query-status-topic: ASYNC_QUERY_STATUS
  upddataset-query-status-topic: UPDDATASET_QUERY_STATUS

aes:
  key: Bonc_123456789ab
file:
  dbpath: /tmp/
  serpath: /root/
hdfs:
  uri: hdfs://10.177.74.192:8020
  user: hh_ser_prod_000_tag_1
  path: /tenants/hh_ser_prod_000_tag_1/work/hh_ser_prod_000_tag_1_push/adb_data/
importparams:
  jar_path: D:\lzk\adb-import-tool.jar
  host: host
  port: 3306
  user: adbuser
  password: pwd
  database: dbname
  encryptPassword: false
  concurrency: 40
  batchSize: 2048
  encoding: UTF-8
  lineSeparator: '\\n'
  delimiter: ','
  maxConcurrentNumOfFilesToImport: 64
  nullAsQuotes: false
  printRowCount: false
  failureSqlPrintLengthLimit: 2000
  disableInsertOnlyPrintSql: false
  skipHeader: false
  windowSize: 128
  escapeSlashAndSingleQuote: true
  ignoreErrors: false
  printErrorSql: true
  printErrorStackTrace: true