server:
  port: 8092
--- #################### 数据库相关配置 ####################
spring:
  # 数据源配置项
  autoconfigure:
    exclude:
      - com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure # 排除 Druid 的自动配置，使用 dynamic-datasource-spring-boot-starter 配置多数据源
  datasource:
    druid: # Druid 【监控】相关的全局配置
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        allow: # 设置白名单，不填则允许所有访问
        url-pattern: /druid/*
        login-username: bonc
        login-password: boncadmin
      filter:
        stat:
          enabled: true
          log-slow-sql: true # 慢 SQL 记录
          slow-sql-millis: 100
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
    dynamic: # 多数据源配置
      druid: # Druid 【连接池】相关的全局配置
        initial-size: 5 # 初始连接数
        min-idle: 10 # 最小连接池数量
        max-active: 20 # 最大连接池数量
        max-wait: 600000 # 配置获取连接等待超时的时间，单位：毫秒
        time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位：毫秒
        min-evictable-idle-time-millis: 300000 # 配置一个连接在池中最小生存的时间，单位：毫秒
        max-evictable-idle-time-millis: 900000 # 配置一个连接在池中最大生存的时间，单位：毫秒
        validation-query: SELECT 1 FROM DUAL # 配置检测连接是否有效
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
      primary: metadata
      datasource:
        metadata:
          url: jdbc:mysql://10.125.21.170:3306/meta_data?allowMultiQueries=true&useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&nullCatalogMeansCurrent=true # MySQL Connector/J 8.X 连接的示例
          username: ENC(agT557PVZ/5F8Ql3aL6cmCcnl/2d+mTR)
          password: ENC(Xy4Hh1RoMyu67BhQ/w4kIqFwCkheOhxf)

        dimdata:
          url: jdbc:mysql://10.125.21.170:3306/dim_data?allowMultiQueries=true&useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&nullCatalogMeansCurrent=true # MySQL Connector/J 8.X 连接的示例
          username: ENC(agT557PVZ/5F8Ql3aL6cmCcnl/2d+mTR)
          password: ENC(Xy4Hh1RoMyu67BhQ/w4kIqFwCkheOhxf)

  # Redis 配置。Redisson 默认的配置足够使用，一般不需要进行调优
  redis:
    password: ENC(//MomNEaC8SK1cdqknXi0Js28BDDE1PW)
    database: 0
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
    sentinel:
      master: label-redis
      nodes: 10.125.11.126:32793,10.125.11.125:32611,10.125.11.124:32874
#################### 服务保障相关配置 ####################
# Lock4j 配置项
lock4j:
  acquire-timeout: 3000 # 获取分布式锁超时时间，默认为 3000 毫秒
  expire: 30000 # 分布式锁的超时时间，默认为 30 毫秒

# Resilience4j 配置项
resilience4j:
  ratelimiter:
    instances:
      backendA:
        limit-for-period: 1 # 每个周期内，允许的请求数。默认为 50
        limit-refresh-period: 60s # 每个周期的时长，单位：微秒。默认为 500
        timeout-duration: 1s # 被限流时，阻塞等待的时长，单位：微秒。默认为 5s
        register-health-indicator: true # 是否注册到健康监测
--- #################### 监控相关配置 ####################
# Actuator 监控端点的配置项
management:
  endpoints:
    web:
      base-path: /actuator # Actuator 提供的 API 接口的根目录。默认为 /actuator
      exposure:
        include: '*' # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 * ，可以开放所有端点。

# Spring Boot Admin 配置项
spring:
  boot:
    admin:
      # Spring Boot Admin Client 客户端的相关配置
      client:
        url: http://127.0.0.1:${server.port}/${spring.boot.admin.context-path} # 设置 Spring Boot Admin Server 地址
        instance:
          prefer-ip: true # 注册实例时，优先使用 IP
      # Spring Boot Admin Server 服务端的相关配置
      context-path: /admin # 配置 Spring

# 日志文件配置
logging:
  file:
    name: ${user.home}/logs/${spring.application.name}.log # 日志文件名，全路径
  level:
    # 配置自己写的 MyBatis Mapper 打印日志
    com.bonc.module.tool.dal.mysql: debug
#################### 芋道相关配置 ####################
# 芋道配置项，设置当前项目所有自定义的配置
yudao:
  captcha:
    enable: false # 本地环境，暂时关闭图片验证码，方便登录等接口的测试
  security:
    token-header: Authorization
    mock-enable: true
    mock-secret: test
  xss:
    enable: false
    exclude-urls: # 如下两个 url，仅仅是为了演示，去掉配置也没关系
      - ${spring.boot.admin.context-path}/** # 不处理 Spring Boot Admin 的请求
      - ${management.endpoints.web.base-path}/** # 不处理 Actuator 的请求
  casapi: http://10.177.86.21:9908/portal/security/rest/findResourcesNewByLoginIdAndAppCode # 关闭演示模式
  appCode: eeee23456
  rocketmq:

    namesrvSend: 10.177.86.36:9876;10.177.86.37:9876
    namesrvAddr: 10.177.86.37:9876;10.177.86.37:9876
    consumerGroup: BONCLABEL_GROUP|BONCLABEL_GROUP1|BONCLABEL_GROUP2
#    namesrvSend: 10.125.119.11:9876
#    namesrvAddr: 10.125.119.11:9876
#    consumerGroup: GID_DISPATCH_GROUP|GID_DISPATCH_GROUP|GID_DISPATCH_GROUP
#    namesrvSend: 82.157.146.232:9876
#    namesrvAddr: 82.157.146.232:9876
#    consumerGroup: GID_DISPATCH_GROUP|GID_DISPATCH_GROUP1|GID_DISPATCH_GROUP2
    urlDetail: http://10.177.76.220:9908/api/assets/dataAssets/rest/v1/assets/dgAssetsAttr/attributeDetail
    urlPublished: http://10.177.76.220:9908/api/assets/dataAssets/rest/v1/assetsInfo/publishedAssetsList
    detailExternal: http://10.177.76.220:9908/api/assets/dataAssets/rest/v1/assets/dgAssetsAttr/getDataItemDetailExternal
    dimExtern: http://10.177.76.220:9908/api/assets/dataAssets/rest/v1/assetsInfo/tagDimExtern

  innerrocketmq:
    nameSrvSend: 10.125.119.11:9876
    producerGroup: GID_DISPATCH_GROUP
    accessKey: ENC(fT3CWt9GDRCTMxTyZsrSF1aIP/LEzspfPJGlaE/RglY=)
    secretKey: ENC(rNSB+VdDlvg8D8u1vVtSVdZXvt1N3lA/A1zD+zhPbHZxYPBKgN2e3g==)
    adb-unicom-topic: adb-unicom-topic  #标签主题
    adb-dim-unicom-topic: adb-dim-unicom-topic  #码表code主题
    adb-tag-unicom-topic: adb-tag-unicom-topic  #分组主题
justauth:
  enabled: true
  type:
    DINGTALK: # 钉钉
      client-id: dingvrnreaje3yqvzhxg
      client-secret: i8E6iZyDvZj51JIb0tYsYfVQYOks9Cq1lgryEjFRqC79P3iJcrxEwT6Qk2QvLrLI
      ignore-check-redirect-uri: true
    WECHAT_ENTERPRISE: # 企业微信
      client-id: wwd411c69a39ad2e54
      client-secret: 1wTb7hYxnpT2TUbIeHGXGo7T0odav1ic10mLdyyATOw
      agent-id: 1000004
      ignore-check-redirect-uri: true
  cache:
    type: REDIS
    prefix: 'social_auth_state:' # 缓存前缀，目前只对 Redis 缓存生效，默认 JUSTAUTH::STATE::
    timeout: 24h # 超时时长，目前只对 Redis 缓存生效，默认 3 分钟

